version: "3"
services:
  selenium:
    container_name: selenium-chrome
    image: seleniarm/standalone-chromium
    ports:
      # Selenium サーバに接続するポート
      - "4444:4444"
      # VNC で接続するポート
      - "5900:5900"
      # Selenium サーバのログを出力するポート
      - "7900:7900"
    # コンテナが使用するメモリの上限を設定
    shm_size: "2gb"
  # Web スクレイピングを実行するコンテナ
  app:
    container_name: scraping-app
    build: ./app
    env_file:
      - .env
    volumes:
      - ./app:/app
    tty: true
